# action to run phantom's automatic maintenance scripts
name: bots

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install findent
      run: sudo apt-get install findent

    - name: Run the bots
      run: |
        git config --global user.email "daniel.price@monash.edu"
        git config --global user.name "Daniel Price"
        git checkout master
        cd scripts
        ./bots.sh --commit
