# This is a basic workflow to help you get started with Actions

name: testkd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SYSTEM: gfortran
      OMP_STACKSIZE: 512M

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install gfortran
      run: sudo apt-get install gfortran

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: compile SETUP=testkd (no MPI)
      run: make SETUP=testkd
        
    - name: run testsuite with SETUP=testkd
      run: ./bin/phantom test

    - name: Install openMPI
      run: sudo apt-get install openmpi-bin openmpi-common libopenmpi-dev

    - name: compile and test SETUP=testkd with MPI
      run: |
        make SETUP=testkd MPI=yes OPENMP=no
        mpirun --allow-run-as-root --mca btl self,sm -np 4 ./bin/phantom test
        
    - name: compile and test GR code
      run: |
        make SETUP=testgr
        ./bin/phantom test gr
