name: Do I get a sticker?

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on raising your first issue on the phantom tracker!'
        pr-message: 'Congratulations on your first phantom pull request. If you send me your mailing address, I will post you some phantom stickers.'
